source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

target 'PDQBook'
pod 'AFNetworking', '~> 3.0'
pod 'Masonry'
pod 'SDWebImage', '~>3.7'
pod 'JSONKit-NoWarning', '~> 1.2'
pod 'FMDB'
pod 'VBFPopFlatButton'
pod 'MJRefresh', '~> 3.0.7'
pod 'UITextView+Placeholder'
pod 'QBPopupMenu'